# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ra', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=80)),
                ('celular', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'aluno',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Arquivoquestao',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('arquivo_questao', models.CharField(max_length=500, unique=True)),
            ],
            options={
                'db_table': 'arquivoquestao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Arquivosresposta',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('arquivos_resposta', models.CharField(max_length=500, unique=True)),
            ],
            options={
                'db_table': 'arquivosresposta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sigla', models.CharField(max_length=5)),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'curso',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cursoturma',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_curso', models.ForeignKey(blank=True, db_column='id_curso', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Curso')),
            ],
            options={
                'db_table': 'cursoturma',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=240, unique=True)),
                ('carga_horaria', models.SmallIntegerField()),
                ('teoria', models.DecimalField(decimal_places=0, max_digits=3)),
                ('pratica', models.DecimalField(decimal_places=0, max_digits=3)),
                ('ementa', models.TextField()),
                ('competencias', models.TextField()),
                ('habilidades', models.TextField()),
                ('conteudo', models.TextField()),
                ('bibliografia_basica', models.TextField()),
                ('bibliografia_complemntar', models.TextField()),
            ],
            options={
                'db_table': 'disciplina',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Disciplinaofertada',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_disciplina', models.CharField(max_length=240)),
                ('ano', models.SmallIntegerField()),
                ('semestre', models.CharField(max_length=1)),
                ('id_disciplina', models.ForeignKey(blank=True, db_column='id_disciplina', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Disciplina')),
            ],
            options={
                'db_table': 'disciplinaofertada',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Gradecurricular',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ano', models.SmallIntegerField()),
                ('semestre', models.CharField(max_length=1)),
                ('id_curso', models.ForeignKey(blank=True, db_column='id_curso', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Curso')),
            ],
            options={
                'db_table': 'gradecurricular',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_aluno', models.ForeignKey(blank=True, db_column='id_aluno', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Aluno')),
            ],
            options={
                'db_table': 'matricula',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('numero', models.SmallIntegerField(unique=True)),
                ('id_gradecurricular', models.ForeignKey(blank=True, db_column='id_gradecurricular', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Gradecurricular')),
            ],
            options={
                'db_table': 'periodo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Periododisciplina',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_disciplina', models.ForeignKey(blank=True, db_column='id_disciplina', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Disciplina')),
                ('id_periodo', models.ForeignKey(blank=True, db_column='id_periodo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Periodo')),
            ],
            options={
                'db_table': 'periododisciplina',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ra', models.IntegerField(blank=True, null=True)),
                ('apelido', models.CharField(max_length=30)),
                ('nome', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=80)),
                ('celular', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'professor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField(unique=True)),
                ('data_limite_entrega', models.CharField(max_length=10)),
                ('descricao', models.TextField()),
                ('datas', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'questao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ra_aluno', models.IntegerField(unique=True)),
                ('data_avaliacao', models.CharField(max_length=10)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4)),
                ('avaliacao', models.TextField()),
                ('descricao', models.TextField()),
                ('data_de_envio', models.CharField(max_length=10)),
                ('id_aluno', models.ForeignKey(blank=True, db_column='id_aluno', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Aluno')),
                ('id_questao', models.ForeignKey(blank=True, db_column='id_questao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Questao')),
            ],
            options={
                'db_table': 'resposta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('turno', models.CharField(max_length=15)),
                ('id_disciplinaofertada', models.ForeignKey(blank=True, db_column='id_disciplinaofertada', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Disciplinaofertada')),
                ('id_professor', models.ForeignKey(blank=True, db_column='id_professor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Professor')),
            ],
            options={
                'db_table': 'turma',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='questao',
            name='id_turma',
            field=models.ForeignKey(blank=True, db_column='id_turma', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Turma'),
        ),
        migrations.AlterUniqueTogether(
            name='professor',
            unique_together=set([('ra', 'apelido')]),
        ),
        migrations.AddField(
            model_name='matricula',
            name='id_turma',
            field=models.ForeignKey(blank=True, db_column='id_turma', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Turma'),
        ),
        migrations.AddField(
            model_name='cursoturma',
            name='id_turma',
            field=models.ForeignKey(blank=True, db_column='id_turma', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Turma'),
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together=set([('sigla', 'nome')]),
        ),
        migrations.AddField(
            model_name='arquivosresposta',
            name='id_resposta',
            field=models.ForeignKey(blank=True, db_column='id_resposta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Resposta'),
        ),
        migrations.AddField(
            model_name='arquivoquestao',
            name='id_questao',
            field=models.ForeignKey(blank=True, db_column='id_questao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Questao'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='id_curso',
            field=models.ForeignKey(blank=True, db_column='id_curso', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Curso'),
        ),
        migrations.AlterUniqueTogether(
            name='gradecurricular',
            unique_together=set([('ano', 'semestre')]),
        ),
        migrations.AlterUniqueTogether(
            name='disciplinaofertada',
            unique_together=set([('nome_disciplina', 'ano', 'semestre')]),
        ),
    ]
